### PR TITLE
Update DTC to 1.6.1

### PR DESCRIPTION
**Pull request by piernov**
This update sadly drops support for 32-bit packages since this is the direction chosen by upstream MSYS2.
Additionally, MSYS2 packages are now compressed with Zstandard (instead of LZMA2) which is not supported by 7-Zip (which `Get-ChocolateyUnzip` uses under the hood), so Zstandard is added as a dependency and used to decompress the archives prior to extraction. I couldn't think of a cleaner way to handle the situation.

Updating the `msys-2.0.dll` library from the `msys2-runtime` package fixes an Unicode-related bug where the file paths could not contain both white spaces and non-ASCII characters.

Original DTC source is at version 1.7.0 but the `dtc` package in MSYS2 hasn't been updated. The `mingw-w64-x86_64-dtc` package in MSYS2 is at version 1.7.0 but has issues with Unicode, so it is better avoided.

### CODE REVIEW

**Comment by carlescufi** [comment]
@piernov my apologies, I missed this PR. Are you still able to follow-up on this?

**Comment by piernov** [comment]
MSYS2 has updated the `dtc` package to 1.7.0, but I noticed there's also a UCRT64 build of `mingw-w64-x86_64-dtc` ( https://packages.msys2.org/package/mingw-w64-ucrt-x86_64-dtc ) which could take care of the Unicode problem as well. I don't know which one is better to choose from.
Upstream has released dtc 1.7.1 recently but the MSYS2 packages have not been updated yet.

I won't have the time to look into that right now but I'll try to get back to it whenever possible. Feel free to do the update on your end if you want to.

**Comment by carlescufi** [comment]
> I won't have the time to look into that right now but I'll try to get back to it whenever possible. Feel free to do the update on your end if you want to.

Thanks @piernov.
I suggest we pull your changes in this PR as-is first, and then we look into upgrading to 1.7.0.

**Comment by piernov** [comment]
Ok then please merge this for now.

**Comment by carlescufi** [comment]
Thanks @piernov!

**Comment by carlescufi** [comment]
@piernov I just pushed it: https://community.chocolatey.org/packages/dtc-msys2#versionhistory

**Pull request merged**
